/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    AppLayout: typeof import('./components/layout/AppLayout.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    ClassNameInput: typeof import('./components/snippet/ClassNameInput.vue')['default']
    CustomCssDialog: typeof import('./components/css/CustomCssDialog.vue')['default']
    DynamicForm: typeof import('./components/snippet/DynamicForm.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    PlaceholderSelector: typeof import('./components/snippet/PlaceholderSelector.vue')['default']
    PreviewIframe: typeof import('./components/preview/PreviewIframe.vue')['default']
    ProjectNameDialog: typeof import('./components/common/ProjectNameDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveConfirmDialog: typeof import('./components/common/SaveConfirmDialog.vue')['default']
    SeoForm: typeof import('./components/template/SeoForm.vue')['default']
    SnippetAddDialog: typeof import('./components/snippet/SnippetAddDialog.vue')['default']
    SnippetConfig: typeof import('./components/snippet/SnippetConfig.vue')['default']
    SnippetList: typeof import('./components/snippet/SnippetList.vue')['default']
    SpacingEditor: typeof import('./components/snippet/SpacingEditor.vue')['default']
    TemplateDropdown: typeof import('./components/template/TemplateDropdown.vue')['default']
    TemplateInfo: typeof import('./components/template/TemplateInfo.vue')['default']
  }
}
